spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    jdbcUrl: jdbc:h2:mem:jackpot;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

jackpot:
  datasource:
    bet:
      jdbcUrl: ${spring.datasource.jdbcUrl}
      liquibase:
        defaultSchema: ~
    contribution:
      jdbcUrl: ${spring.datasource.jdbcUrl}
      liquibase:
        defaultSchema: ~
    reward:
      jdbcUrl: ${spring.datasource.jdbcUrl}
      liquibase:
        defaultSchema: ~
